services:
  medichaser:
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - medichaser_data:/app/data
    ports:
      - 7681:7681

volumes:
  medichaser_data: