services:
  mediczuwacz_ttyd:
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mediczuwacz_data:/app/data
    ports:
      - 7681:7681

volumes:
  mediczuwacz_data: