name: push image to dockerhub on release
on:
  release:
    types:
      - created

jobs:
  push_latest_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            root-cache-pip
            var-cache-apt
            var-lib-apt
          key: ${{ runner.os }}-cache-${{ hashFiles('Dockerfile') }}

      - name: inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.2.0
        with:
          cache-map: |
            {
              "root-cache-pip": "/root/.cache/pip",
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push mediczuwacz_ttyd image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          push: true
          tags: rafsaf/mediczuwacz_ttyd:${{ github.ref_name }},rafsaf/mediczuwacz_ttyd:latest
          platforms: linux/amd64
