name: push image to dockerhub on release
on:
  push:
    branches:
      - "master"
    tags:

jobs:
  push_latest_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: rafsaf/mediczuwacz_ttyd

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: cache-mount
          key: cache-mount-${{ runner.os }}-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            cache-mount-${{ runner.os }}-

      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-dir: cache-mount
          dockerfile: Dockerfile
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push mediczuwacz_ttyd image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
